apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-base
  namespace: istio-system
spec:
  chart:
    spec:
      chart: base
      version: 1.28.0
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: istio-system
  interval: 1h0m0s
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istiod
  namespace: istio-system
spec:
  dependsOn:
    - name: istio-base
  chart:
    spec:
      chart: istiod
      version: 1.28.0
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: istio-system
  interval: 1h0m0s
  values:
    cni:
      enabled: true
    global:
      logAsJson: true
    meshConfig:
      serviceSettings:
        - settings:
            clusterLocal: true
          hosts:
            - "kiali.istio-system.svc.cluster.local"
      accessLogFile: "/dev/stdout"
      accessLogEncoding: "JSON"
      enableTracing: false
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cni
  namespace: kube-system
spec:
  chart:
    spec:
      chart: cni
      version: 1.28.0
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: istio-system
  interval: 1h0m0s
  values:
    global:
      resourceScope: all
    cni:
      cniBinDir: /home/kubernetes/bin
