---
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: airflow-webhook
  namespace: argo
spec:
  service:
    ports:
    - port: 12000
      targetPort: 12000
  webhook:
    airflow-webhook:
      endpoint: /airflow
      method: POST
      port: "12000"
