---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: promstack
  namespace: monitoring
spec:
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 75.9.0
      sourceRef:
        kind: HelmRepository
        name: promstack
        namespace: monitoring
  interval: 1h0m0s
  values:
    alertmanager:
        enabled: true
        alertmanagerSpec:
          storage:
            volumeClaimTemplate:
              spec:
              storageClassName: standard-rwo
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 1Gi
    prometheus:
      prometheusSpec:
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: standard-rwo
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 5Gi
    grafana:
      additionalDataSources: 
        - name: loki
          access: proxy
          basicAuth: false
          editable: false
          orgId: 1
          type: loki
          url: http://loki.monitoring.svc.cluster.local:3100
          version: 1
