apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: webapp
  namespace: ai
spec:
  interval: 1m
  chart:
    spec:
      chart: k8s/helm-charts/webapp
      sourceRef:
        kind: GitRepository
        name: webapp
        namespace: ai
