apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: github-actions-controller
  namespace: github-actions
spec:
  chart:
    spec:
      chart: gha-runner-scale-set-controller
      version: 0.13.0
      sourceRef:
        kind: HelmRepository
        name: github-actions
        namespace: github-actions
  interval: 1h0m0s
