ci:
  - changed-files:
      - any-glob-to-any-file: ".github/**/*"
flux:
  - changed-files:
      - any-glob-to-any-file: "clusters/**/*"
kubernetes:
  - changed-files:
      - any-glob-to-any-file: "infra/**/*"
infra-app:
  - changed-files:
      - any-glob-to-any-file: 'infra/**/*'
      - all-globs-to-all-files: '!infra/secrets/*'
secrets:
  - changed-files:
      - any-glob-to-any-file: "infra/secrets/*"
