apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: signoz
    namespace: monitoring
spec:
    chart:
        spec:
            chart: signoz
            version: 0.99.0
            sourceRef:
                kind: HelmRepository
                name: signoz
                namespace: monitoring
    interval: 1h0m0s
    values:
        mode: deployment
        replicaCount: 3
        image:
            repository: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib
        command:
            name: otelcol-contrib
        config:
            global:
              storageClass: standard-rwo
            clickhouse:
              persistence:
                storageClass: standard-rwo
            signoz:
              persistence:
                storageClass: standard-rwo