apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: cnpg-operator
    namespace: cnpg-operator
spec:
    chart:
        spec:
            chart: cloudnative-pg
            version: 0.24.0
            sourceRef:
                kind: HelmRepository
                name: cloudnative-pg
                namespace: cnpg-operator
    interval: 1h0m0s
