apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: argo-events
    namespace: argo
spec:
    chart:
        spec:
            chart: argo-events
            version: 2.4.16
            sourceRef:
                kind: HelmRepository
                name: argo
                namespace: argo
    interval: 1h0m0s