apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: external-secrets
    namespace: external-secrets
spec:
    chart:
        spec:
            chart: external-secrets
            version: 0.18.2
            sourceRef:
                kind: HelmRepository
                name: external-secrets
                namespace: external-secrets
    interval: 1h0m0s
