---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: finure
  namespace: kafka
  labels:
    strimzi.io/cluster: finure
spec:
  authentication:
    type: tls
  template:
    secret:
      metadata:
        annotations:
          reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
          reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "ai,keda"
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: finure
          patternType: literal
        operations:
          - Read
          - Describe
          - Write
          - Create
        host: "*"
      - resource:
          type: group
          name: "finure"
          patternType: prefix
        operations:
          - Read
        host: "*"
