---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github
  namespace: ai
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: github
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ .dockerconfigjson | toString }}"
  data:
    - secretKey: dockerconfigjson
      remoteRef:
        key: infra/data/github
        property: dockerconfigjson