---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github
  namespace: ai
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: github
  dataFrom:
  - extract:
      key: infra/data/github
