apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-backend
  namespace: external-secrets
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local.:8200"
      version: "v2"
      auth:
        kubernetes:
          mountPath: finure
          role: external-secrets # read-only role
          serviceAccountRef:
            namespace: external-secrets
            name: external-secrets
          secretRef:
            namespace: external-secrets
            name: external-secrets-sa-token
            key: token
---
apiVersion: v1
kind: Secret
metadata:
  name: external-secrets-sa-token
  namespace: external-secrets
  annotations:
    kubernetes.io/service-account.name: external-secrets
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: role-tokenreview-binding
  namespace: external-secrets
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: external-secrets
    namespace: external-secrets
