apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: finure-app
  namespace: cnpg-database
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: finure-app
  dataFrom:
  - extract:
      key: infra/data/finure-app
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: finure-app
  namespace: ai
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: finure-app
  dataFrom:
  - extract:
      key: infra/data/finure-app
