---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ghcr
  namespace: ai
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: ghcr
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ .dockerconfigjson | toString }}"
  data:
    - secretKey: dockerconfigjson
      remoteRef:
        key: infra/data/github
        property: dockerconfigjson
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ghcr
  namespace: airflow
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: ghcr
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ .dockerconfigjson | toString }}"
  data:
    - secretKey: dockerconfigjson
      remoteRef:
        key: infra/data/github
        property: dockerconfigjson
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ghcr
  namespace: argo
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: ghcr
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ .dockerconfigjson | toString }}"
  data:
    - secretKey: dockerconfigjson
      remoteRef:
        key: infra/data/github
        property: dockerconfigjson
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ghcr
  namespace: tekton-pipelines
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: ghcr
    template:
      type: kubernetes.io/dockerconfigjson
      metadata:
        annotations:
          tekton.dev/docker-0: https://ghcr.io
      data:
        .dockerconfigjson: "{{ .dockerconfigjson | toString }}"
  data:
    - secretKey: dockerconfigjson
      remoteRef:
        key: infra/data/github
        property: dockerconfigjson
