---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-actions
  namespace: github-actions
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: github-actions
  dataFrom:
  - extract:
      key: infra/data/github-actions
