---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname secrets
  namespace: &namespace external-secrets
spec:
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  interval: 30m
  timeout: 5m
  path: "./infra/secrets/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra
    namespace: flux-system
  wait: true
  dependsOn:
    - name: external-secrets
      namespace: external-secrets
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: external-secrets
      namespace: external-secrets
  