apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: slack
  namespace: flux-system
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: slack
  dataFrom:
  - extract:
      key: infra/data/slack
