---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tekton
  namespace: tekton-pipelines
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: tekton
  dataFrom:
  - extract:
      key: infra/data/github
