apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keda
  namespace: keda
spec:
  chart:
    spec:
      chart: keda
      version: 2.17.2
      sourceRef:
        kind: HelmRepository
        name: kedacore
        namespace: keda
  interval: 1h0m0s