apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: cnpg
    namespace: cnpg-system
spec:
    chart:
        spec:
            chart: cluster
            version: 0.24.0
            sourceRef:
                kind: HelmRepository
                name: cloudnative-pg
                namespace: cnpg-system
    interval: 1h0m0s
