apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname vault
  namespace: &namespace vault
spec:
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  interval: 30m
  timeout: 5m
  path: "./infra/finure/vault/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra
    namespace: flux-system
  wait: true
