apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: reflector
  namespace: tools
spec:
  interval: 1m
  chart:
    spec:
      chart: reflector
      version: 9.1.22
      sourceRef:
        kind: HelmRepository
        name: reflector
        namespace: tools
  values:
    serviceAccount: 
      name: reflector