apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: app-frontend
  namespace: ai
spec:
  interval: 1m
  chart:
    spec:
      chart: k8s/helm-charts/app-frontend
      sourceRef:
        kind: GitRepository
        name: app-frontend
        namespace: ai
