apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname external-dns
  namespace: &namespace external-dns
spec:
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  interval: 30m
  timeout: 5m
  path: "./infra/finure/external-dns/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra
    namespace: flux-system
  wait: true
  dependsOn:
    - name: secrets
      namespace: external-secrets
    - name: istio
      namespace: istio-system
