apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kafka-operator
  namespace: kafka
spec:
  chart:
    spec:
      chart: strimzi-kafka-operator
      version: 0.47.0
      sourceRef:
        kind: HelmRepository
        name: strimzi
        namespace: kafka
  interval: 1h0m0s
  values:
    serviceAccount: kafka
