apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: istio-base
    namespace: istio-system
spec:
    chart:
        spec:
            chart: base
            version: 1.26.2
            sourceRef:
                kind: HelmRepository
                name: istio
                namespace: istio-system
    interval: 1h0m0s
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: istiod
    namespace: istio-system
spec:
    dependsOn:
      - name: istio-base
    chart:
        spec:
            chart: istiod
            version: 1.26.2
            sourceRef:
                kind: HelmRepository
                name: istio
                namespace: istio-system
    interval: 1h0m0s
    values:
      global:
        logAsJson: true
      meshConfig:
        serviceSettings:
          - settings:
              clusterLocal: true
            hosts:
              - "kiali.istio-system.svc.cluster.local"
        accessLogFile: "/dev/stdout"
        accessLogEncoding: "JSON"
        enableTracing: false
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: istio-ingressgateway
    namespace: istio-system
spec:
    dependsOn:
      - name: istio-base
      - name: istiod
    chart:
        spec:
            chart: gateway
            version: 1.26.2
            sourceRef:
                kind: HelmRepository
                name: istio
                namespace: istio-system
    interval: 1h0m0s
    values:
      service:
        annotations: 
          external-dns.alpha.kubernetes.io/hostname: "prometheus.clokesh.me,alertmanager.clokesh.me,vault.clokesh.me,grafana.clokesh.me,atlantis.clokesh.me,kiali.clokesh.me,opencost.clokesh.me,jenkins.clokesh.me"
          external-dns.alpha.kubernetes.io/cloudflare-proxied: "true" # for individual ingress (istio igw here) - can be set for all CF dns records using the --cloudflare-proxied flag in external-dns args
