apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: atlantis
    namespace: tools
spec:
    chart:
        spec:
            chart: atlantis
            version: 5.18.0
            sourceRef:
                kind: HelmRepository
                name: atlantis
                namespace: tools
    interval: 1h0m0s
    values:
        orgAllowlist: github.com/Finure/*
        vcsSecretName: atlantis-github
        githubApp:
            id: "1608341"
            installationId: "75934933"
            slug: finure-bot
        service:
            type: ClusterIP
        serviceAccount:
            name: atlantis
            annotations:
                iam.gke.io/gcp-service-account: atlantis@finure-465001.iam.gserviceaccount.com
        repoConfig: ENC[AES256_GCM,data:CogLUaiEWFf7vR23coZ+oPqRcOrk0+TA5aM6lRCO3KGjmsuXU2LWyzN0NnsWv4sLFJ/H9958o8S7bQhL8MEOCqSjA/CTTpRm6XrLQxR1CauvX1GyzEsooaitXe2P3OhP6YV7Qy2D4VKjq3nNBeLyr5ByTwattpbNRalKNaXz4IPpkVbslR3Bax1jkU9bd+oRiyHEHpTwFxvY/SA2Ac/QHFkD5blPZKfCYU+MOxYe/7nDceoEXZCOSkI4GAFLFj1q9ObuFRvEfJyuxsV7IQHhCtJOwH4hzV2iLdQIHDTe//jKVugScnwsmSOVKO2OHfWluVIaEWd18FBR4XoPnhbeJmQ37hhQ8mPzHfJuQx4v+s6SoNDb8uxBGAwnzJwmeQqrsbYkGv3pQz7079YnYTE/xs2wOjUo4nVB1fbkTwOehkQD+7lceVP6N1LSQLUnNFkDIB7wFS9WzIkMkSRpQvzSFtY3lKLDiPApt6mplgEmyvZTo0GoCsvUe18aizEtDIgLK+oaO0yyntS1/02vzH7aPst9NtnGIHpQ9hE30Lue7RXGjefJfsdSjQs0nwjGY1fQcl+4qJ8QqwhldOQpRsHDKsyZ7bQCYyF4Bhy3Rg+yAcJ4Iz8Qb1UXgfDPaJRyfnxuSdwRRegt/AT5pBs5++1v3jXpY07c5oXMft2CUlL18Na29U3yZf0Yv4zx/X5jjUPkmZ0ilvXBccvuMVlPr2TShhKzZ/PIJ85gfLnu7Lz1Tz8R7LHe0KqQNIbECNmgbtlUSwOONnxpyab+62QYMs3vxvsFFM3qsug9ECMIhVTsNvDf16fIyFOLX2Nuco2Co42U6WKKlg2axvyG5HW48lV0TGngAvI83pkdkmOO4vOMgRfH2+zQ5ysU7DLHavKn1VhQ9q++JLABgOg7TN8YfUaT/GaeslJpjQ493w==,iv:lgu4NK7Jll81IvCvlVhJ7wFf9pCDx1KF+a00r8g9o3U=,tag:UEnb48/UiYcb1h+WrdGdbQ==,type:str]
        extraVolumes:
            - name: generator
              secret:
                secretName: atlantis
                defaultMode: 511
                items:
                    - key: generator
                      path: scripts/repo-config-generator.sh
            - name: policies
              secret:
                secretName: atlantis
                defaultMode: 511
                items:
                    - key: policies
                      path: default.rego
        extraVolumeMounts:
            - name: generator
              mountPath: /etc/atl
            - name: policies
              mountPath: /atlantis-data/policies
        extraArgs:
            - --silence-no-projects
            - --silence-vcs-status-no-plans
            - --vcs-status-name=finure
            - --hide-prev-plan-comments
            - --enable-policy-checks
            - --quiet-policy-checks
            - --repo-allowlist=github.com/Finure/*
        environmentSecrets:
            - name: GITHUB_TOKEN
              secretKeyRef:
                name: atlantis-env
                key: GITHUB_TOKEN
sops:
    gcp_kms:
        - resource_id: projects/finure-465001/locations/global/keyRings/gcp-finure/cryptoKeys/sops-key
          created_at: "2025-07-18T11:36:37Z"
          enc: CiQA2FBvQ13l+C30v9rhVi5JjleeVIcqqU6s7u3dRRuoi5OetWESSQD6dMGYF4Uw9JXOLAGwfrsFUGUyooqrMHpXfIYmLf80vBNObfgVpdDelxi8Hf7LIYHL8Fj86CZiJrscT4fwUAmacteqGq8RUdk=
    lastmodified: "2025-08-22T01:52:44Z"
    mac: ENC[AES256_GCM,data:Gd4xDbWV3dtz2PyTk+i/8Yg/1RZG7YCkjmsgeFiMKRiE7F7Fj7MOPV2CC5RdWo7Qdaikjf76r3bs0yAnUZwJ6zxvhZGExh9rXIwmtXxaQwOD/+3Xzz0nHpo8912OK+M5xToxdtyBVwMX5acxD7uN424oPnf2l/Ycu+8qXh8+zRI=,iv:hYx8XD/Q9SuOX477CBClp73GInEn+xAWDYoQnEKQoS8=,tag:21I2jYBTjvblpkaQ5tWcFw==,type:str]
    encrypted_regex: (^.*repoConfig$)
    version: 3.10.2
