apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: atlantis
    namespace: tools
spec:
    chart:
        spec:
            chart: atlantis
            version: 5.18.0
            sourceRef:
                kind: HelmRepository
                name: atlantis
                namespace: tools
    interval: 1h0m0s
    values:
        orgAllowlist: github.com/Finure/*
        vcsSecretName: atlantis-github
        githubApp:
            id: "1608341"
            installationId: "75934933"
            slug: finure-bot
        service:
            type: ClusterIP
        serviceAccount:
            name: atlantis
            annotations:
                iam.gke.io/gcp-service-account: atlantis@finure-465001.iam.gserviceaccount.com
        repoConfig: ENC[AES256_GCM,data:SMZuRSTrGhBpz6wgAc5rJgk9CtIRndyNzqOdl2RrByuYtbkWBAK+Esuv2XAW1euV5UL3FlS3bbhtP7RnQiOVqMEkwcFqMqWMvXl+ZrzdlUqDtiTzFV4U50Cfyksp/RO2EGlMg13xrGgpmLVQ0i74xumkrXv8aL1xKYAenNcBXiAs9QRybFK8lR25YGzx0hXsaJ0pXVZasH2JUVRqtNLsDbAnQ7oFOdY7CsCFfuJWpPSQWC4ZThHMD9Zs7im8QLNRcu/zAUyMqdlISLHRQcovsrUZwiOHYcohsSInfop5U6iaSfdUtN6mSswlsvsZETc/kmkZ+qOfUfm7GEgcNy3xgzUHWXh0gKYHRRu8V+e3xDmEuTsWQ3hU4HGbN/p2tqiwk+0qFdC6gFsOeNOLnqd+7Yv7/jSD7p0EQDp0cvbEJiytLkdk/b9nNsARi0gYYthW/SUH9+gjre5auv9End7MRamzTYt7q/hpzv6PNrQJkL/PdcnqknlnFWzWk30R5N2Zdj3MJLvYuCYYCClQMziK2DP35xjRXUn+XcgdXyu2xd4XZWlOhOsNop4S+oti12dKrlcaIdJcXSS4I6eRRPl6gHPt8GljbDZhI+JNF8apnf01yo6/RQXdL9h1BSrUJLmHhKgjGMpS5iNO/mvfbeYNJK+y0/HkoznsVwGrKwWJoa4QzobECp4q6mmuAUB7yLplbCBGD2VYPdmWM/Zc0nvuOZwxVSTKUpb4wvAFdVAsOw+XcA+Ojez2sybD7saA9dLeSc8erCG/t8e6qDzToDcM4+5kW/XdhfB5ZqI5ZyNLDwFGKTSFs20uRnr6OndOj5YTCDIEbl1RO88RDGO+NvwnwGnlpVSnZk9cPS55biMwFlzaB+CwPyRFEpaMnkKUsO06KMhW5mWmG1ER6M4pLcKc+9c=,iv:Ohkzl1lEUSWfh12tEN3d7pOANNAId2LclU2F5EyRi+Y=,tag:R4W07XKiIzyKBRXfyKN03w==,type:str]
        extraVolumes:
            - name: generator
              secret:
                secretName: atlantis
                defaultMode: 511
                items:
                    - key: generator
                      path: scripts/repo-config-generator.sh
            - name: policies
              secret:
                secretName: atlantis
                defaultMode: 511
                items:
                    - key: policies
                      path: default.rego
        extraVolumeMounts:
            - name: generator
              mountPath: /etc/atl
            - name: policies
              mountPath: /atlantis-data/policies
        extraArgs:
            - --silence-no-projects
            - --silence-vcs-status-no-plans
            - --vcs-status-name=finure
            - --hide-prev-plan-comments
            - --enable-policy-checks
            - --quiet-policy-checks
            - --repo-allowlist=github.com/Finure/*
        environmentSecrets:
            - name: GITHUB_TOKEN
              secretKeyRef:
                name: atlantis-env
                key: GITHUB_TOKEN
sops:
    gcp_kms:
        - resource_id: projects/finure-465001/locations/global/keyRings/gcp-finure/cryptoKeys/sops-key
          created_at: "2025-07-18T11:36:37Z"
          enc: CiQA2FBvQ13l+C30v9rhVi5JjleeVIcqqU6s7u3dRRuoi5OetWESSQD6dMGYF4Uw9JXOLAGwfrsFUGUyooqrMHpXfIYmLf80vBNObfgVpdDelxi8Hf7LIYHL8Fj86CZiJrscT4fwUAmacteqGq8RUdk=
    lastmodified: "2025-07-20T15:41:51Z"
    mac: ENC[AES256_GCM,data:7NLv0s60E3XlEupTA3RDbWxyUFp0xVMaPGp3XYilcrqEIu/lX+Shfh9zBgcAlaMPsGWdQ/FJ1LI2Qkd5wGVjHA09nBSINLMGS/9anI6VzhWykzGKCn9GhpXIGp9XE4p+DPPu+G8V/gIJrwjb5xjOB9+ktGRj9jlt1+12mSZftq0=,iv:DnyTsAsmKiDVQItFGo5NikGvKaF+YgEx6suDeakiOr4=,tag:6AgSCDjlXsBfoNs1asfPtg==,type:str]
    encrypted_regex: (^.*repoConfig$)
    version: 3.10.2
