apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: kserve-resources
    namespace: kserve
spec:
    chart:
        spec:
            chart: kserve
            version: v0.12.0
            sourceRef:
                kind: HelmRepository
                name: kserve
                namespace: kserve
    interval: 1h0m0s
