---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname production-terraform-drift
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/production/terraform-drift
  prune: true
  dependsOn:
    - name: secrets
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname production-app-seedjob
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/production/app-seedjob
  prune: true
  dependsOn:
    - name: kafka-secrets
    - name: tekton-pipelines
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname production-app-backend
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/production/app-backend
  prune: true
  dependsOn:
    - name: production-app-seedjob
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname production-app-frontend
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/production/app-frontend
  prune: true
  dependsOn:
    - name: production-app-gateway
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname production-app-gateway
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/production/app-gateway
  prune: true
  dependsOn:
    - name: production-app-backend
