---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname istio
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infra/istio
  prune: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname monitoring
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infra/monitoring
  prune: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname vault
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infra/vault
  prune: true
  decryption:
    provider: sops
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname external-secrets
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infra/external-secrets
  prune: true
  dependsOn:
    - name: vault
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: external-secrets
      namespace: external-secrets
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname external-secrets-backend
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infra/external-secrets-backend
  prune: true
  dependsOn:
    - name: external-secrets
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname secrets
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infra/secrets
  prune: true
  dependsOn:
    - name: external-secrets-backend
  healthChecks:
    - apiVersion: v1
      kind: Secret
      name: cloudflare
      namespace: external-dns
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname external-dns
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infra/external-dns
  prune: true
  dependsOn:
    - name: external-secrets-backend
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname istio-resources
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infra/istio-resources
  prune: true
  dependsOn:
    - name: istio
