apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gotk-components.yaml
  - gotk-sync.yaml
  - infra.yaml
  - apps.yaml
patches:
  - patch: |
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: kustomize-controller
        annotations:
          iam.gke.io/gcp-service-account: sops-sa@finure-465001.iam.gserviceaccount.com
    target:
      kind: ServiceAccount
      name: kustomize-controller
  - patch: |
      apiVersion: v1
      kind: Kustomization
      metadata:
        name: flux-system
      spec:
        decryption:
          provider: sops
    target:
      kind: Kustomization
      name: flux-system
