apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: cnpg-cluster
    namespace: cnpg-database
spec:
    chart:
        spec:
            chart: cluster
            version: 0.3.1
            sourceRef:
                kind: HelmRepository
                name: cloudnative-pg
                namespace: cnpg-operator
    interval: 1h0m0s
    values:
        cluster:
          serviceAccountTemplate:
            metadata:
                name: cnpg-cluster
                annotations:
                    iam.gke.io/gcp-service-account: cnpg-cluster@finure-465001.iam.gserviceaccount.com
          initdb:
            database: finure
          roles:
            - name: tekton-results
              ensure: present
              passwordSecret:
                name: tekton-results-postgres
              login: true
            - name: finure
              ensure: present
              passwordSecret:
                name: finure-app
              login: true
        backups:
            enabled: true
            provider: google
            google:
                bucket: "finure-cnpg"
            scheduledBackups:
                - name: daily-backup
                  schedule: "0 0 0 * * *" 
                  backupOwnerReference: self
        storage:
          size: 10Gi
          storageClass: "standard-rwo"