apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: cnpg-cluster
    namespace: cnpg-database
spec:
    chart:
        spec:
            chart: cluster
            version: 0.3.1
            sourceRef:
                kind: HelmRepository
                name: cloudnative-pg
                namespace: cnpg-system
    interval: 1h0m0s
    values:
        backups:
            enabled: true
            provider: google
            google:
            bucket: "finure-cnpg"
            scheduledBackups:
                - name: daily-backup
                  schedule: "0 0 0 * * *" 
                  backupOwnerReference: self
        storage:
          size: 10Gi
          storageClass: "standard-rwo"