apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: kserve-crd
    namespace: kserve
spec:
    chart:
        spec:
            chart: kserve-crd
            version: v0.12.0
            sourceRef:
                kind: HelmRepository
                name: kserve
                namespace: kserve
    interval: 1h0m0s
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kserve
  namespace: kserve
  annotations:
    iam.gke.io/gcp-service-account: "kserve@finure-465001.iam.gserviceaccount.com"
