---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: terraform-drift
  namespace: tools
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/Finure/terraform-drift
  secretRef:
    name: github