apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: request-limits
spec:
  rules:
  - name: force-default-resources
    match:
      resources:
        kinds:
        - Pod
        namespaces:
        - ai
    mutate:
      foreach:
      - list: "request.object.spec.containers"
        patchStrategicMerge:
          spec:
            containers:
            - name: "{{ element.name }}"
              resources:
                requests:
                  cpu: "100m"
                  memory: "256Mi"
                limits:
                  cpu: "100m"
                  memory: "256Mi"
---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: deny-privileged-pods
spec:
  validationFailureAction: Enforce
  rules:
  - name: deny-privileged
    match:
      resources:
        kinds:
        - Pod
        - Deployment
        - StatefulSet
        - DaemonSet
        - Job
        - CronJob
        namespaces:
        - ai
    validate:
      message: "Privileged pods are not allowed in this namespace"
      deny:
        conditions:
          any:
          - key: "{{ request.object.spec.template.spec.containers[].securityContext.privileged || `false` }}"
            operator: Equals
            value: true
---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: default-labels
spec:
  rules:
  - name: add-label
    match:
      resources:
        kinds:
        - Deployment
        - StatefulSet
        - DaemonSet
        - Job
        - CronJob
        - Pod
        namespaces:
        - ai
    mutate:
      patchStrategicMerge:
        metadata:
          labels:
            team: "infra"
