apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: github-actions-scale-set
  namespace: github-actions
spec:
  chart:
    spec:
      chart: gha-runner-scale-set
      version: 0.13.0
      sourceRef:
        kind: HelmRepository
        name: github-actions
        namespace: github-actions
  interval: 1h0m0s
  values:
    githubConfigUrl: https://github.com/Finure
    githubConfigSecret: github-actions
    runnerScaleSetName: finure-workflows
    minRunners: 0
    maxRunners: 3
    containerMode:
      type: dind
