apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: eck-operator
  namespace: logging
spec:
  chart:
    spec:
      chart: eck-operator
      version: 3.0.0
      sourceRef:
        kind: HelmRepository
        name: elastic
        namespace: logging
  interval: 1h0m0s
