apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fluent-bit
  namespace: logging
spec:
  interval: 1m
  chart:
    spec:
      chart: fluent-bit
      version: 0.50.0
      sourceRef:
        kind: HelmRepository
        name: fluent-bit
        namespace: logging
  values:
    config:
      inputs: |
        [INPUT]
            Name tail
            Path /var/log/containers/*.log
            multiline.parser cri
            Tag kube.*
            Mem_Buf_Limit 5MB    
      customParsers: |
        [PARSER]
            Name   json_or_text
            Format json
            Time_Key time
            Time_Format %Y-%m-%dT%H:%M:%S.%LZ
      filters: |
        [FILTER]
            Name kubernetes
            Match kube.*
            Merge_Log On
            Keep_Log Off
            K8S-Logging.Parser On
            K8S-Logging.Exclude On
            Annotations off
        [FILTER]
            Name parser
            Match kube.*
            Key_Name log
            Parser json_or_text
            Reserve_Data True
            Preserve_Key False
        [FILTER]
            Name    grep
            Match   kube.*
            Exclude namespace_name logging    
      outputs: |
        [OUTPUT]
            Name loki
            Match kube.*
            Host loki.logging.svc.cluster.local
            Port 3100
            Labels job=fluentbit, namespace=${namespace}, pod=${pod_name}, service=${service_name}
            Auto_Kubernetes_Labels On
