apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fluent-bit
  namespace: logging
spec:
  interval: 1m
  chart:
    spec:
      chart: fluent-bit
      version: 0.50.0
      sourceRef:
        kind: HelmRepository
        name: fluent-bit-1
        namespace: logging
  values:
    config:
      inputs: |
        [INPUT]
            Name tail
            Path /var/log/containers/*.log
            multiline.parser cri
            Tag kube.*
            Mem_Buf_Limit 5MB    
      filters: |
        [FILTER]
            Name kubernetes
            Match kube.*
            Merge_Log On
            Keep_Log Off
            K8S-Logging.Parser On
            K8S-Logging.Exclude On
            Annotations off 
        [FILTER]
            Name record_modifier
            Match kube.*
            Remove_key stream
            Remove_key _p
      outputs: |
        [OUTPUT]
            Name loki
            Match kube.*
            Host loki.logging.svc.cluster.local
            Port 3100
            Labels agent=fluent-bit, namespace=$kubernetes['namespace_name'], pod=$kubernetes['pod_name'], container=$kubernetes['container_name']
            Auto_Kubernetes_Labels On
