apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  chart:
    spec:
      chart: loki
      version: 6.30.1
      sourceRef:
        kind: HelmRepository
        name: loki
        namespace: monitoring
  interval: 1h0m0s
  values:
    loki:
      image:
        registry: docker.io
        repository: grafana/loki
        tag: 3.4.2
      commonConfig:
        replication_factor: 1
      schemaConfig:
        configs:
          - from: "2024-04-01"
            store: tsdb
            object_store: gcs
            schema: v13
            index:
              prefix: loki_index_
              period: 24h
      limits_config:
        allow_structured_metadata: true
        retention_period: 168h
        split_queries_by_interval: 15m
        volume_enabled: true
      storage:
        type: gcs
        bucketNames:
          chunks: "finure-loki"
          ruler: "finure-loki"
        gcs:
          chunkBufferSize: 0
          requestTimeout: "0s"
          enableHttp2: true
      auth_enabled: false
    storage_config:
      gcs:
        bucket_name: "finure-loki"
      tsdb_shipper:
        active_index_directory: /data/tsdb-index
        cache_location: /data/tsdb-cache
        cache_ttl: 12h
        flush_interval: 1m
        object_store: gcs
        bucket: "finure-loki"
    serviceAccount:
      create: true
      annotations:
        "iam.gke.io/gcp-service-account": "loki-gcs@finure-465001.iam.gserviceaccount.com"
    minio:
      enabled: false
    deploymentMode: SingleBinary
    singleBinary:
      replicas: 1
      persistence:
        storageClass: standard-rwo
        accessModes:
          - ReadWriteOnce
        size: 10Gi
    backend:
      replicas: 0
    read:
      replicas: 0
    write:
      replicas: 0
    chunksCache:
      allocatedMemory: 500
