apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: logging
spec:
  chart:
    spec:
      chart: loki
      version: 6.30.1
      sourceRef:
        kind: HelmRepository
        name: loki
        namespace: logging
  interval: 1h0m0s
  values:
    serviceAccount:
      create: true
      name: loki-sa
      annotations:
        eks.amazonaws.com/role-arn: "iam.gke.io/gcp-service-account: loki-gcs@finure-465001.iam.gserviceaccount.com"
    loki:
      auth_enabled: false
      commonConfig:
        replication_factor: 1
      storage:
        type: gcs
        bucketNames:
          chunks: finure-loki/chunks
          ruler: finure-loki/ruler
          admin: finure-loki/admin
        object_store:
          type: gcs
          gcs:
            bucket_name: finure-loki
      schemaConfig:
        configs:
          - from: "2024-04-01"
            store: tsdb
            object_store: gcs
            schema: v13
            index:
              prefix: index_
              period: 24h
      storage_config:
        gcs:
          bucket_name: finure-loki
    chunksCache:
      enabled: false
    memcached:
      enabled: false
    memcachedExporter:
      enabled: false
    backend:
    replicas: 0
    read:
    replicas: 0
    write:
    replicas: 0
