apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: external-dns
    namespace: external-dns
spec:
    chart:
        spec:
            chart: external-dns
            version: 1.17.0
            sourceRef:
                kind: HelmRepository
                name: external-dns
                namespace: external-dns
    interval: 1h0m0s
    values:
        provider:
          name: cloudflare
        env:
        - name: CF_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: cloudflare
              key: apiKey
        - name: CF_API_EMAIL
          valueFrom:
            secretKeyRef:
              name: cloudflare
              key: email
