apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: argo-workflows
    namespace: tools
spec:
    chart:
        spec:
            chart: argo-workflows
            version: 0.45.20
            sourceRef:
                kind: HelmRepository
                name: argo
                namespace: tools
    interval: 1h0m0s
    values:
      controller:
        telemetryConfig:
          enabled: true
        serviceMonitor:
          enabled: true
        workflowNamespaces:
          - ai
        serviceAccount:
          create: true
          name: "argo"
          annotations:
              iam.gke.io/gcp-service-account: argo-workflows@finure-465001.iam.gserviceaccount.com
      useStaticCredentials: false
      artifactRepository:
        gcs:
          bucket: finure-argo
