apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: chaos-mesh
    namespace: chaos-mesh
spec:
    chart:
        spec:
            chart: chaos-mesh
            version: 2.8.0
            sourceRef:
                kind: HelmRepository
                name: chaos-mesh
                namespace: chaos-mesh
    interval: 1h0m0s
    values:
      controllerManager:
        enableFilterNamespace: true
      chaosDaemon:
        runtime: containerd
        socketPath: /run/containerd/containerd.sock
