apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: snyk
  namespace: tekton-pipelines
spec:
  params:
    - name: severity
      description: Severity threshold (low|medium|high|critical)
      type: string
      default: "high"
  workspaces:
    - name: shared-workspace
      description: Source code context including Dockerfile.
    - name: github
      description: Optional workspace to provide .docker/config.json for registry auth.
  steps:
    - name: snyk-scan
      image: python:3.12-slim
      workingDir: $(workspaces.shared-workspace.path)/app
      env:
        - name: SNYK_TOKEN
          valueFrom:
            secretKeyRef:
              name: tekton
              key: SNYK_TOKEN
      script: |
        #!/bin/sh
        set -eu pipefail
        apt-get update -y
        apt-get install -y --no-install-recommends curl ca-certificates
        pip install -r requirements.txt
        curl -fsSL https://static.snyk.io/cli/latest/snyk-linux -o /usr/local/bin/snyk
        chmod +x /usr/local/bin/snyk

        snyk --version
        snyk test --severity-threshold=$(params.severity)
