name: Flux Local

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  flux:
    name: flux-diff
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cluster_path:
          - infra/finure
        resource:
          - helmrelease
          - kustomization
        exclude:
          - cluster_path: infra/finure/helm-releases/.sops.yaml
    steps:
    - name: Print matrix path and resource
      run: echo "Running on path ${{ matrix.cluster_path }}"
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c # v46
      with:
        files: |
          clusters/**/helmrelease*.yaml
          clusters/**/kustomization*.yaml
          infra/**/**.yaml

    - name: Setup Flux CLI
      if: steps.changed-files.outputs.any_changed == 'true'
      uses: fluxcd/flux2/action@v2.2.3

    - name: Run flux diff
      if: steps.changed-files.outputs.any_changed == 'true'
      uses: allenporter/flux-local/action/diff@4.3.1
      id: diff
      with:
        live-branch: main
        path: ${{ matrix.cluster_path }}
        resource: ${{ matrix.resource }}

    - name: PR Comment with diff
      if: steps.diff.outputs.diff != ''
      uses: mshick/add-pr-comment@v2
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        message-id: flux-diff
        message-failure: Unable to post diff
        message: |
          `````diff
          ${{ steps.diff.outputs.diff }}
          `````
