name: Lint

on:
  workflow_dispatch:
  pull_request:
    branches:
    - main

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  actionlint:
    name: actionlint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        persist-credentials: false

    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c # v46
      with:
        patterns: |-
          .github/workflows/*.yaml
          .github/workflows/*.yml

    - name: Run actionlint
      if: steps.changed-files.outputs.changed_files != '[]'
      uses: reviewdog/action-actionlint@a5524e1c19e62881d79c1f1b9b6f09f16356e281 # v1.65.2
      with:
        actionlint_config: .github/actionlint.yaml
        file_pattern: ${{ join(fromJSON(steps.changed-files.outputs.changed_files), ' ') }}

  yamllint:
    name: yamllint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        persist-credentials: false

    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c # v46
      with:
        patterns: |-
          **/*.yaml
          **/*.yml

    - name: Install yamllint
      if: steps.changed-files.outputs.changed_files != '[]'
      shell: bash
      run: |
        pip install --user yamllint

    - name: Run yamllint
      if: steps.changed-files.outputs.changed_files != '[]'
      shell: bash
      run: |
        yamllint --config-file .yamllint.yaml --format github ${{ join(fromJSON(steps.changed-files.outputs.changed_files), ' ') }}

  markdownlint:
    name: markdownlint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        persist-credentials: false

    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c # v46
      with:
        patterns: |-
          **/*.md

    - name: Run markdownlint-cli2
      if: steps.changed-files.outputs.changed_files != '[]'
      uses: nosborn/github-action-markdown-cli@v3.5.0
      with:
        markdownlint_config: .markdownlint.yaml
        file_pattern: ${{ join(fromJSON(steps.changed-files.outputs.changed_files), ' ') }}

  lint_success:
    needs:
    - actionlint
    - yamllint
    - markdownlint
    if: ${{ !cancelled() }}
    name: Lint successful
    runs-on: ubuntu-latest
    steps:
    - name: Check job status
      if: ${{ contains(needs.*.result, 'failure') }}
      run: exit 1
