name: Talisman scan

on:
  pull_request:
    branches:
      - main

jobs:
  talisman-scan:
    runs-on: ubuntu-latest
    name: Run Talisman to detect secrets

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go (Talisman requires Go)
        uses: actions/setup-go@v4
        with:
          go-version: 1.23

      - name: Install Talisman
        run: |
          go install github.com/thoughtworks/talisman/cmd/talisman@v1.37.0
          echo "$HOME/go/bin" >> $GITHUB_PATH

      - name: Run Talisman scan
        run: talisman --scan
