name: Talisman scan

on:
  pull_request:
    branches:
      - main

jobs:
  talisman-scan:
    runs-on: ubuntu-latest
    name: Run Talisman to detect secrets

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go (Talisman requires Go)
        uses: actions/setup-go@v4
        with:
          go-version: 1.23

      - name: Install Talisman
        run: |
          curl -sL https://github.com/thoughtworks/talisman/releases/latest/download/talisman-linux-amd64 -o talisman
          chmod +x talisman
          sudo mv talisman /usr/local/bin/

      - name: Run Talisman scan
        run: talisman --scan
