name: Kubernetes API Validation

on:
  pull_request:
    paths:
      - '**.yaml'
      - '**.yml'

jobs:
  validate:
    name: Validate YAML and HelmReleases
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Install tools (helm, kubeconform, yq)
        run: |
          curl -L https://get.helm.sh/helm-v3.14.3-linux-amd64.tar.gz | tar xz
          sudo mv linux-amd64/helm /usr/local/bin/

          curl -L https://github.com/yannh/kubeconform/releases/latest/download/kubeconform-linux-amd64.tar.gz | tar xz
          sudo mv kubeconform /usr/local/bin/

          pip install yq

      - name: chmod validation script
        run: chmod +x scripts/validate.sh

      - name: Validate changed manifests
        run: .github/scripts/validate.sh
